In [ ]:
# ADVANCED TECHNIQUES 1 
import numpy as np
try:
    a = np.array([1, 2, 3])
    b = np.array([[1], [2], [3]])
    result = a + b
    print("Broadcasting Result:\n", result)
except ValueError as e:
    print(f"Broadcasting error: {e}")

Broadcasting Result:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [2]:
# ADVANCED TECHNIQUES 2
identity = np.eye(3)
matrix = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
print("Matrix + Identity:\n", matrix + identity)

Matrix + Identity:
 [[ 3.  3.  4.]
 [ 1.  1.  6.]
 [ 7.  8. 10.]]


In [3]:
# ADVANCED TECHNIQUES 3
data = np.array([1, 2, np.nan, 4, np.inf])
# This keeps only finite numbers and removes NaNs/Infs
cleaned = data[np.isfinite(data)]
print("Cleaned Data:", cleaned)

Cleaned Data: [1. 2. 4.]


In [6]:
# ADVANCED TECHNIQUES 4
import pandas as pd
df = pd.DataFrame({
    "Name": ["Jona", "Jones", "Jonalyn", "Jonx"],
    "Score": [85, None, 92, 88]
})
df_cleaned = df.dropna()
print("Cleaned DataFrame:\n", df_cleaned)

Cleaned DataFrame:
       Name  Score
0     Jona   85.0
2  Jonalyn   92.0
3     Jonx   88.0


In [7]:
# ADVANCED TECHNIQUES 5
df = pd.DataFrame({
    "X": [1, 2, 3],
    "Y": [4, 5, 6]
})
df["Log_X"] = np.log(df["X"])
df["Sqrt_Y"] = np.sqrt(df["Y"])
print("Transformed DataFrame:\n", df)

Transformed DataFrame:
    X  Y     Log_X    Sqrt_Y
0  1  4  0.000000  2.000000
1  2  5  0.693147  2.236068
2  3  6  1.098612  2.449490
