In [1]:
# PROCEDURE 1: Creating NumPy Arrays
# Updated: Try It Results
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10, 12, 15.])
print("\nYears of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], [80, 90, 100], [110, 120, 130]])
print("\nSalary Matrix:\n", salaries)

identity_matrix = np.eye(3)

print("\nUpdated Years of Experience:", years_exp)
print("\nUpdated Salary Matrix:\n", salaries)
print("\n3x3 Identity Matrix:\n", identity_matrix)


Years of Experience: [ 1.  3.  5.  7. 10. 12. 15.]

Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]]

Updated Years of Experience: [ 1.  3.  5.  7. 10. 12. 15.]

Updated Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# PROCEDURE 2: Array Operations
# Updated: Try It Results
# Step 1: Element-wise subtraction
exp_minus_3 = years_exp - 3 # Subtract 3 years to all experience values
print("Years - 3:", exp_minus_3)

# Step 2: Element-wise division
exp_div_2 = years_exp / 2 # divide all values by 2
print("Years / 2:", exp_div_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("\nDot Product:", dot_result)

# Apply exponential function
np.set_printoptions(precision=4, suppress=True)
exp_values = np.exp(years_exp)
print("\nExponential of years:\n", exp_values)

# Apply logarithmic function
np.set_printoptions(precision=4, suppress=True)
log_salaries = np.log(salaries)
print("\nLogarithm of salaries:\n", log_salaries)

Years - 3: [-2.  0.  2.  4.  7.  9. 12.]
Years / 2: [0.5 1.5 2.5 3.5 5.  6.  7.5]

Dot Product: 32

Exponential of years:
 [      2.7183      20.0855     148.4132    1096.6332   22026.4658
  162754.7914 3269017.3725]

Logarithm of salaries:
 [[3.912  4.0943 4.2485]
 [4.382  4.4998 4.6052]
 [4.7005 4.7875 4.8675]]


In [3]:
# PROCEDURE 3: Indexing and Slicing
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2]) # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

# Updated: Try It Results
print("Try It Results:")

# Reverse the 1D years_exp array
reversed_years = years_exp[::-1]
print("\nReversed Years:", reversed_years)

# Get a subgroup: First 2 rows and first 2 columns
salary_subgroup = salaries[0:2, 0:2]
print("\nSalary Subgroup (Top-left 2x2):\n", salary_subgroup)

# Get another subgroup: Last 2 rows and last 2 columns
# (Using negative indexing for fun)
bottom_right = salaries[-2:, -2:]
print("\nSalary Subgroup (Bottom-right):\n", bottom_right)


First year of experience: 1.0
First two salaries: [50 60]
Second column salaries: [ 60  90 120]
Last year of experience: 15.0
Try It Results:

Reversed Years: [15. 12. 10.  7.  5.  3.  1.]

Salary Subgroup (Top-left 2x2):
 [[50 60]
 [80 90]]

Salary Subgroup (Bottom-right):
 [[ 90 100]
 [120 130]]


In [4]:
# PROCEDURE 4: Reshaping and Dimensions
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

# Updated: Try It Results
data = np.arange(1, 7)

# Reshape to 3 rows and 2 columns
reshaped_3x2 = data.reshape(3, 2)
print("Try It Results:")
print("\nReshaped into 3x2:\n", reshaped_3x2)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
Try It Results:

Reshaped into 3x2:
 [[1 2]
 [3 4]
 [5 6]]


In [5]:
# PROCEDURE 5: Broadcasing in NumPy
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n", salaries_with_bonus)

# Updated: Try It Results
scaling_factor = 1.50

# Multiply the entire salaries matrix by the factor
scaled_salaries = salaries * scaling_factor

print("Try It Results:")
print(f"\nSalaries after {scaling_factor} scaling factor:\n", scaled_salaries)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]
 [115 130 145]]
Try It Results:

Salaries after 1.5 scaling factor:
 [[ 75.  90. 105.]
 [120. 135. 150.]
 [165. 180. 195.]]


In [6]:
# PROCEDURE 6: Statistical Operations
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

# Updated: Try It Results
# Compute median for years of experience
median_exp = np.median(years_exp)
print("\nTry It Results:")
print("\nMedian experience:", median_exp)

# Compute the 25th and 75th percentiles for salaries
p25 = np.percentile(salaries, 25)
p75 = np.percentile(salaries, 75)

print(f"25th percentile of salaries: {p25}")
print(f"75th percentile of salaries: {p75}")

Mean experience: 7.571428571428571
Std deviation of experience: 4.655477353371521
Max salary: 130 Min salary: 50
Sum of all salaries: 810

Try It Results:

Median experience: 7.0
25th percentile of salaries: 70.0
75th percentile of salaries: 110.0


In [7]:
# PROCEDURE 7: NumPy Functions on Arrays
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

# Updated: Try It Results
# Apply square root to years of experience
sqrt_exp = np.sqrt(years_exp)
print("\nTry It Results:")
print("\nSquare root of experience:", sqrt_exp)

# Define a custom function
def calculate_tax(salary_row):
    return salary_row * 0.10

# Apply it along axis 1 (rows)
tax_per_person = np.apply_along_axis(calculate_tax, 1, salaries)

print("\n10% Tax deduction per person (by row):\n", tax_per_person)

Sine of angles: [0.     0.7071 1.    ]
Cosine of angles: [1.     0.7071 0.    ]
Sum of Salaries per person: [180 270 360]

Try It Results:

Square root of experience: [1.     1.7321 2.2361 2.6458 3.1623 3.4641 3.873 ]

10% Tax deduction per person (by row):
 [[ 5.  6.  7.]
 [ 8.  9. 10.]
 [11. 12. 13.]]


In [8]:
# PROCEDURE 8: Integrating NumPy and Pandas for Analysis
import pandas as pd

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("\nDataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("\nCorrelation Matrix:\n", df_data.corr())

# Updated: Try It Results
# Try It: Overall column statistics using NumPy functions
mean_X = np.mean(df_data['X'])
median_Y = np.median(df_data['Y'])

print("\nTry It Results:")
print(f"\nOverall Mean of Column X: {mean_X:.2f}")
print(f"Overall Median of Column Y: {median_Y:.2f}")

# Create a new column by squaring Column Z
df_data['Square_Z'] = np.square(df_data['Z'])

# Create a new column by applying exponential to Column X
df_data['Exp_X'] = np.exp(df_data['X'])

print("\nDataFrame with New Transformations:\n", df_data)

Generated Data:
     X   Y   Z
0  17   4  25
1  32  10  35
2  15  11   3
3  25  17  25
4   6  14  12

DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  17   4  25  2.833213  2.000000
1  32  10  35  3.465736  3.162278
2  15  11   3  2.708050  3.316625
3  25  17  25  3.218876  4.123106
4   6  14  12  1.791759  3.741657

Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.010349  0.778006  0.965439 -0.001877
Y      -0.010349  1.000000 -0.180330 -0.113178  0.993778
Z       0.778006 -0.180330  1.000000  0.680668 -0.205483
Log_X   0.965439 -0.113178  0.680668  1.000000 -0.114810
Sqrt_Y -0.001877  0.993778 -0.205483 -0.114810  1.000000

Try It Results:

Overall Mean of Column X: 19.00
Overall Median of Column Y: 11.00

DataFrame with New Transformations:
     X   Y   Z     Log_X    Sqrt_Y  Square_Z         Exp_X
0  17   4  25  2.833213  2.000000       625  2.415495e+07
1  32  10  35  3.465736  3.162278      1225  7.896296

In [9]:
# PROCEDURE 9: Importing and Summarizing Data Using Pandas
# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
np.set_printoptions(precision=4, suppress=True)
df_imported = pd.read_csv('sample_data.csv')
print("\nImported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
np.set_printoptions(precision=4, suppress=True)
summary_stats = df_imported.describe()
print("\nSummary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
np.set_printoptions(precision=4, suppress=True)
print("\nColumn Means:\n", df_imported.mean())
print("\nColumn Standard Deviations:\n", df_imported.std())

# Updated: Try It Results
# Try It: Add a new calculated column 'Sum_XY'
np.set_printoptions(precision=4, suppress=True)
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']

# Display the updated DataFrame to verify the new column
np.set_printoptions(precision=4, suppress=True)
print("\nUpdated DataFrame with Sum_XY column:\n", df_imported)

# Try It: Save the modified DataFrame to a new file
np.set_printoptions(precision=4, suppress=True)
new_filename = 'modified_sample_data.csv'
df_imported.to_csv(new_filename, index=False)

np.set_printoptions(precision=4, suppress=True)
print(f"\nModified data successfully saved to '{new_filename}'.")

Data saved to 'sample_data.csv'.

Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y  Square_Z         Exp_X
0  17   4  25  2.833213  2.000000       625  2.415495e+07
1  32  10  35  3.465736  3.162278      1225  7.896296e+13
2  15  11   3  2.708050  3.316625         9  3.269017e+06
3  25  17  25  3.218876  4.123106       625  7.200490e+10
4   6  14  12  1.791759  3.741657       144  4.034288e+02

Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y     Square_Z  \
count   5.000000   5.000000   5.000000  5.000000  5.000000     5.000000   
mean   19.000000  11.200000  20.000000  2.803527  3.268733   525.600000   
std     9.924717   4.868265  12.529964  0.641230  0.802639   479.951873   
min     6.000000   4.000000   3.000000  1.791759  2.000000     9.000000   
25%    15.000000  10.000000  12.000000  2.708050  3.162278   144.000000   
50%    17.000000  11.000000  25.000000  2.833213  3.316625   625.000000   
75%    25.000000  14.000000  25.000000  3.218876  

In [10]:
# PROCEDURE 10: Data Grouping and Aggregation
# Step 1: Load the dataset (This is now working!)
df_kaggle = pd.read_csv('survey_results_public.csv')

# Step 2: Select columns (Fixed the names to match the CSV)
# Note: In the 2023 survey, compensation is 'ConvertedCompYearly'
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]

# Step 3: Clean the data
df_clean = df_subset.dropna().copy()

# Step 4: Categorize experience 
# We must convert 'YearsCodePro' to numbers first because it's stored as text
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
df_clean = df_clean.dropna() 

df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5 & 6: Group and Reset Index
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()
grouped_data = grouped_data.reset_index()

print("Formatted Grouped Data:\n", grouped_data.head())

# Updated: Try It Results
print("Try It Results:")

# 1. Change the grouping to EdLevel
ed_group = df_clean.groupby('EdLevel')['ConvertedCompYearly'].mean().sort_values(ascending=False)
print("\n1. Average Salary by Education Level:\n", ed_group)

# 2. Compute median and standard deviation
stats_by_country = df_clean.groupby('Country')['ConvertedCompYearly'].agg(['median', 'std'])
print("\n2. Median and Std Dev per Country (Top 5):\n", stats_by_country.head())

# 3. Explore top 10 countries with highest average compensation
top_10_countries = df_clean.groupby('Country')['ConvertedCompYearly'].mean().sort_values(ascending=False).head(10).round(2)
print("\n3. Top 10 Countries by Average Compensation:\n", top_10_countries)

Formatted Grouped Data:
        Country ExperienceLevel  ConvertedCompYearly
0  Afghanistan          Junior         1.031035e+06
1  Afghanistan          Senior         3.300000e+01
2      Albania          Junior         2.564647e+04
3      Albania          Senior         1.397000e+05
4      Algeria          Junior         9.103895e+03
Try It Results:

1. Average Salary by Education Level:
 EdLevel
Primary/elementary school                                                             358681.449761
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                        159445.678094
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          104938.502816
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        97124.658707
Associate degree (A.A., A.S., etc.)                                                    91136.695003
Some college/university study without earning a degree                                 90738.206916

In [11]:
# DATA AND OBSERVATION 1
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Ma. Jonalyn Ebrada's Array: [ 45  20  84  76   9   4  96 102  64  24]
Mean: 52.4 Std Dev: 34.911889092399456


In [12]:
# DATA AND OBSERVATION 2
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Ma. Jonalyn Ebrada's Matrix:
 [[13 20 20 21]
 [12  9  4  6]
 [24  1 23  9]]
Row sums: [74 31 57]
Column sums: [49 30 47 36]


In [13]:
# DATA AND OBSERVATION 3
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Ma. Jonalyn Ebrada's 3D Array:
 [[[12 19 19]
  [20 11  8]
  [ 3  5 23]]

 [[ 0 22  8]
  [10 25 16]
  [ 5 16 10]]

 [[13 14 13]
  [ 3 20  5]
  [23 12 22]]]
Slice[:,1,:]:
 [[20 11  8]
 [10 25 16]
 [ 3 20  5]]


In [14]:
# DATA AND OBSERVATION 4
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Ma. Jonalyn Ebrada's Original: [ 45  20  84  76   9   4  96 102  64  24]
Filtered subset: [45 20  9 24]


In [15]:
# DATA AND OBSERVATION 5
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[13 20]
 [20 21]]
Matrix B:
 [[12  9]
 [ 4  6]]
A @ B:
 [[236 237]
 [324 306]]
Determinant of A: -126.99999999999999


In [16]:
# DATA AND OBSERVATION 6
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Ma. Jonalyn Ebrada's Angles: [0.     0.8976 1.7952 2.6928 3.5904 4.488  5.3856 6.2832]
Sine: [ 0.      0.7818  0.9749  0.4339 -0.4339 -0.9749 -0.7818 -0.    ]
Cosine: [ 1.      0.6235 -0.2225 -0.901  -0.901  -0.2225  0.6235  1.    ]


In [17]:
# DATA AND OBSERVATION 7
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Ma. Jonalyn Ebrada's Modified 4x4 Array:
 [[ 0 20  0 21]
 [12  9  4  6]
 [ 0  1  0  9]
 [11 17  6 17]]


In [18]:
# DATA AND OBSERVATION 8
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Ma. Jonalyn Ebrada's Scores: [ 44  19  83  75   8   3  95 101  63  23]
Grades: ['Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']


In [19]:
# DATA AND OBSERVATION 9
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[13 20 20 21]
 [12  9  4  6]
 [24  1 23  9]]
Flattened: [13 20 20 21 12  9  4  6 24  1 23  9]
Transposed:
 [[13 12 24]
 [20  9  1]
 [20  4 23]
 [21  6  9]]


In [20]:
# DATA AND OBSERVATION 10
import numpy as np
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)


Array with conditional replacements:
 [[13 -1 -1]
 [21 -1  9]
 [-1 -1 -1]]


In [21]:
# DATA AND OBSERVATION 11
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50,
STUDENT_ID%100+50,5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
print(df)

                 Name  Score  YearsCodePro
0  Ma. Jonalyn Ebrada     50             3
1  Ma. Jonalyn Ebrada     25             5
2  Ma. Jonalyn Ebrada     89            23
3  Ma. Jonalyn Ebrada     81             0
4  Ma. Jonalyn Ebrada     14            22


In [22]:
# DATA AND OBSERVATION 12
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor     90811.5
Master       70861.5
PhD         131091.0
Name: ConvertedComp, dtype: float64


In [23]:
# DATA AND OBSERVATION 13
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
2           UK         131091
0  Philippines         127084
4      Germany          74440
1          USA          67283
3       Canada          54539


In [24]:
# DATA AND OBSERVATION 14
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)


                 Name  YearsCodePro
0  Ma. Jonalyn Ebrada            12
1  Ma. Jonalyn Ebrada            19
2  Ma. Jonalyn Ebrada            19
3  Ma. Jonalyn Ebrada            20
4  Ma. Jonalyn Ebrada            11


In [25]:
# DATA AND OBSERVATION 15
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0         127084  100-150k
1          67283   50-100k
2         131091  100-150k
3          54539   50-100k
4          74440   50-100k


In [26]:
# DATA AND OBSERVATION 16
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.
# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)


   ConvertedComp    LogComp
0         127084  11.752604
1          67283  11.116663
2         131091  11.783647
3          54539  10.906671
4          74440  11.217749


In [27]:
# DATA AND OBSERVATION 17
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.174799
ConvertedComp     -0.174799       1.000000


In [28]:
# DATA AND OBSERVATION 18
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel':['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(summary)

    EdLevel      mean    median           std
0  Bachelor   90811.5   90811.5  51297.061441
1    Master   70861.5   70861.5   5060.763233
2       PhD  131091.0  131091.0           NaN


In [29]:
# DATA AND OBSERVATION 19
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)

# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})

threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(df)


   ConvertedComp HighPay
0         127084     Yes
1          67283      No
2         131091     Yes
3          54539      No
4          74440      No


In [30]:
# DATA AND OBSERVATION 20
import numpy as np
import pandas as pd
STUDENT_NAME = "Ma. Jonalyn Ebrada"
STUDENT_ID = 250756

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada        54539.0   54539
Germany       74440.0   74440
Philippines  127084.0  127084
UK           131091.0  131091
USA           67283.0   67283
